### PR TITLE
Adding vagrant support

### PR DESCRIPTION
**Pull request by jamesrf**
Hi!  This code allows this to be used with vagrant -- just have to type "vagrant up" and your evergreen server is available on `10.10.11.11` (can be changed in the Vagrantfile)

This did require adding:
```
become: true
become_user: opensrf
```

To many ansible config lines -- I'm not sure if this might interfere with other ways these ansible scripts are being used?

Signed-off-by: James <james.fournie@gmail.com>

### CODE REVIEW

**Comment by jamesrf** [comment]
I should note that if you happen to "vagrant halt" your VM, you need to log back in and restart apache and opensrf.

**Comment by berick** [comment]
Thanks, James.  I'll take a look.  I likely won't test Vagrant specifically, but can at least verify the changes don't break anything.  At a glance, they look fine.

**Comment by berick** [comment]
James, I'd like to rename "Vagrantfile" to "Vagrantfile.example", then add "Vagrantfile" to the gitignore file so it can ignore local changes.  Sound good?

**Comment by berick** [comment]
James, I tried testing this today.  It looks like there are a few cases (eg-web.xml) where the become / become_user entries are duplicates of existing entries.  For example:

```
- name: AngularJS npm test                                                     
  become: true                                                                 
  become_user: opensrf                                                         
  environment:                                                                 
    CHROME_BIN: /usr/bin/chromium-browser                                      
  shell: >                                                                     
    cd {{repo_base}}/Evergreen/Open-ILS/web/js/ui/default/staff                
    && npm run test                                                            
  become: true                                                                 
  become_user: opensrf 
```
This produces runtime warnings:

[WARNING]: While constructing a mapping from /home/berick/code/evergreen-ansible-installer/evergreen/eg-web.yml, line 40, column 3, found a
duplicate dict key (become_user). Using last defined value only.

**Comment by jamesrf** [comment]
Thanks Bill -- I made those changes on the branch

**Comment by berick** [comment]
Thanks, James!  Merged to ubuntu-18.04 branch.  Added a follow up commit to gitignore Vagrantfile.

**Pull request merged**
